language: node_js
os: linux
dist: trusty
sudo: required
node_js:
  - 5.2.0

env:
  - secure: "dG18oZYO14eMwOL9UR7QJ38QUq/7f+tGb/4GW39oHA73CTLzbRG+FT7yod1lefTYdzVOO+fxWDQ5ciTvlX2pZyjhg3PilrWiKKz4zP0+Wm8ZY47bkmPW4AOAi9IqPMlRseQD9dhlxXZw8Z0vm9GwdP1ef2UAG27IWCxXp2oZ0XE="
  - secure: "k1Odn5mnXvqijmLuwW3zQZeshXOoqd8rcB2xQJoVI8fetHtL2wjwuLGNzuTyiDhUIf5ZyaQrmdiD8L0WM9nwN4aoa3azFw5SruzEY+0pw1SaliEXyzfg8FljbKA53ueIq0kXXgWbaj93pMOz6rz+U926DlkarHPGVZnYlgtQ6zs="

addons:
  ssh_known_hosts: dev.openki.xyz

cache:
  directories:
    - "$HOME/.meteor"
    - "$HOME/.npm"
    - "$HOME/node_modules"
    - ".meteor/local/build"
    - ".meteor/local/bundler-cache"
    - ".meteor/local/isopacks"
    - ".meteor/local/mirrors"
    - ".meteor/local/plugin-cache"
    - "node_modules"

before_install:
  # Download Meteor
  - PATH=$PATH:$HOME/.meteor
  - if [ ! -e $HOME/.meteor/meteor ]; then curl -k https://install.meteor.com | sh; fi

install:
  - git fetch --unshallow
  - meteor npm install --production

script:
  - echo travis:$sshpassword | sudo chpasswd
  - sudo sed -i 's/ChallengeResponseAuthentication no/ChallengeResponseAuthentication yes/' /etc/ssh/sshd_config
  - sudo service ssh restart
  - sudo apt-get install sshpass
  - sshpass -p $sshpassword ssh -R 9999:localhost:22 -o StrictHostKeyChecking=no travisci@$bouncehostip
  # Test for JS errors
  - meteor npm run js-lint -- .
  # Run unit-tests
  - meteor npm run test
  # Run end-to-end tests
  - meteor npm run test-app

before_deploy:
  - openssl aes-256-cbc -K $encrypted_b653f608ad1c_key -iv $encrypted_b653f608ad1c_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
  # Add an IPv6 config - see the corresponding Travis issue
  # https://github.com/travis-ci/travis-ci/issues/8361
  - sudo sh -c 'echo 0 > /proc/sys/net/ipv6/conf/all/disable_ipv6'

deploy:
  provider: script
  skip_cleanup: true
  script: bin/deploy dev
  on:
    branch: automated-deployment
