language: node_js
dist: trusty
node_js:
  - 5.2.0

cache:
  directories:
    - "$HOME/.meteor"
    - "$HOME/.npm"
    - "$HOME/node_modules"
    - ".meteor/local/build"
    - ".meteor/local/bundler-cache"
    - ".meteor/local/isopacks"
    - ".meteor/local/mirrors"
    - ".meteor/local/plugin-cache"
    - "node_modules"

before_install:
  # Download Meteor
  - PATH=$PATH:$HOME/.meteor
  - if [ ! -e $HOME/.meteor/meteor ]; then curl -k https://install.meteor.com | sh; fi

  # Install chimp
  - npm install -g chimp

  # Cache Selenium & ChromeDriver
  - chimp --browser=phantomjs --path=bin

install:
  - meteor npm install

script:
  - ./bin/test
