language: node_js
os: linux
dist: trusty
sudo: required
node_js:
  - 5.2.0

addons:
  ssh_known_hosts: dev.openki.xyz

cache:
  directories:
    - "$HOME/.meteor"
    - "$HOME/.npm"
    - "$HOME/node_modules"
    - ".meteor/local/build"
    - ".meteor/local/bundler-cache"
    - ".meteor/local/isopacks"
    - ".meteor/local/mirrors"
    - ".meteor/local/plugin-cache"
    - "node_modules"

before_install:
  # Download Meteor
  - PATH=$PATH:$HOME/.meteor
  - if [ ! -e $HOME/.meteor/meteor ]; then curl -k https://install.meteor.com | sh; fi

install:
  - git fetch --unshallow
  - meteor npm install --production

script:
  # Add an IPv6 config - see the corresponding Travis issue
  # https://github.com/travis-ci/travis-ci/issues/8361
  - sudo sh -c 'echo 0 > /proc/sys/net/ipv6/conf/all/disable_ipv6'
  - sudo apt-get install miredo
  - sleep 20
  - ifconfig
  - sudo ip addr show
  - ping -c 4 dev.openki.xyz
  # Test for JS errors
  - meteor npm run js-lint -- .
  # Run unit-tests
  - meteor npm run test
  # Run end-to-end tests
  - meteor npm run test-app

before_deploy:
  - openssl aes-256-cbc -K $encrypted_b653f608ad1c_key -iv $encrypted_b653f608ad1c_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa

deploy:
  provider: script
  skip_cleanup: true
  script: bin/deploy dev
  on:
    branch: automated-deployment
